set_property SRC_FILE_INFO {cfile:C:/Users/ga690/Desktop/HWpractice/T_flipflop_no_oneshottrigger/T_flipflop_no_oneshottrigger.srcs/constrs_1/new/T_flipflop_no_oneshottrigger.xdc rfile:../../../T_flipflop_no_oneshottrigger.srcs/constrs_1/new/T_flipflop_no_oneshottrigger.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y1 [get_ports T]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports Q]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K4 [get_ports clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N8 [get_ports rst]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
